apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventorySelectorTemplate
metadata:
  name: site-a-vm-01-selector
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        matchLabels:
          site-id: site-a
          test-group: 2-sites-5-vms
          hostname: node1-sitea
---
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: site-a-vm-01
  namespace: fleet-default
  labels:
    site-id: site-a
    test-group: 2-sites-5-vms
    hostname: node1-sitea
spec:
  kubernetesVersion: v1.33.5+k3s1
  rkeConfig:
    machinePools:
    - name: control-plane
      quantity: 1
      etcdRole: true
      controlPlaneRole: true
      workerRole: true
      machineConfigRef:
        kind: MachineInventorySelectorTemplate
        name: site-a-vm-01-selector
        apiVersion: elemental.cattle.io/v1beta1
