apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: site-b-registration
  namespace: fleet-default
spec:
  machineInventoryLabels:
    site-id: site-b
    test-group: 2-sites-5-vms
    hostname: ${Runtime/Hostname}
  config:
    cloud-config:
      users:
        - name: root
          passwd: linux
          ssh_authorized_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGDKrMEscmfI/N4oGtSjQ6r/MtjvFVDKI58/RMQJw3um cledorze@home
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5cke7RYaET4MGBNVMfa0joBPyIslSNZAgrOz4zbRRJlnuuWYaoD7AcIpN+INZykllLjRXsDtggYjLEed5BvrNEo87CBZrgwjd3KQ9Qp1awKPyXeIG80VROO+KTI4JoS9uC5pRxENEo/yWjpGMaHSeZoSDGKfLjnJbxru4pJhKYFlDjEd/eFZ6Ho4ZSV1CMHRM9Tn5/3jPKd3do5qDYl/UhoG/M0Pw222iGu6/DAtGpfVPrLv1Kp3gOTTcw1qcYWept3CPgr9Q60rCyGmpCJ+E5+kqExG/EdgfRFjKeneNYdqqnFKKOAV6cwLcCvMYbQ5GVwmsnX6pAyvS8bWYOui/lbM/LbZ1hiMDjmOSFg5cFTWz1C1Zlg1m+UhCFkIK5aAm5i5TNwwus2OH8Lo5rwSydCNtsKlxk2FX1oKhqaCiCi+FK9d+1TMCw/Swr5TvFTXONeR2JveQfET6R0cOrl+2zdqEsLWdRfwStAL+h4L/OiDO+Q99t3QndKRjsFYBZAs= tofix@osxie.local
        - name: tofix
          passwd: linux
          ssh_authorized_keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5cke7RYaET4MGBNVMfa0joBPyIslSNZAgrOz4zbRRJlnuuWYaoD7AcIpN+INZykllLjRXsDtggYjLEed5BvrNEo87CBZrgwjd3KQ9Qp1awKPyXeIG80VROO+KTI4JoS9uC5pRxENEo/yWjpGMaHSeZoSDGKfLjnJbxru4pJhKYFlDjEd/eFZ6Ho4ZSV1CMHRM9Tn5/3jPKd3do5qDYl/UhoG/M0Pw222iGu6/DAtGpfVPrLv1Kp3gOTTcw1qcYWept3CPgr9Q60rCyGmpCJ+E5+kqExG/EdgfRFjKeneNYdqqnFKKOAV6cwLcCvMYbQ5GVwmsnX6pAyvS8bWYOui/lbM/LbZ1hiMDjmOSFg5cFTWz1C1Zlg1m+UhCFkIK5aAm5i5TNwwus2OH8Lo5rwSydCNtsKlxk2FX1oKhqaCiCi+FK9d+1TMCw/Swr5TvFTXONeR2JveQfET6R0cOrl+2zdqEsLWdRfwStAL+h4L/OiDO+Q99t3QndKRjsFYBZAs= tofix@osxie.local
        - name: cledorze
          passwd: linux
          ssh_authorized_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGDKrMEscmfI/N4oGtSjQ6r/MtjvFVDKI58/RMQJw3um cledorze@home
    elemental:
      install:
        device-selector:
          - key: Name
            operator: In
            values:
              - /dev/sda
              - /dev/vda
              - /dev/nvme0
          - key: Size
            operator: Gt
            values:
              - 25Gi
        reboot: true
        snapshotter:
          type: btrfs
      reset:
        reboot: true
        reset-oem: true
        reset-persistent: true

